# Encrypt this file with ansible-vault, or configure an external vault provider.
# This file is unencrypted for demonstration purposes only.
service_account_user: "admin"
service_account_password: "!f5admin"
